/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctlr_Paciente;
import Modelo.Paciente;
import static Vista.verPacientes.tblPaciente;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class verInternados extends javax.swing.JFrame {
    private static verInternados instance;
    private String nombreSeleccionado;
    private String motivoSeleccionado;
    private Salida salidaFrame;
    /**
     * Creates new form Consultar
     */
    private int paginaActual = 1;
    private final int registrosPorPagina = 20;

    public verInternados() {
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        this.cargarTabla(); 
        instance = this;
        this.salidaFrame = salidaFrame;

    }

    public void setSalidaFrame(Salida salidaFrame) {
        this.salidaFrame = salidaFrame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInternar = new javax.swing.JTable();
        btnCambiarArea = new javax.swing.JButton();
        btnDarAlta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pacientes internados");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Buscar Paciente");

        txtCriterio.setBackground(new java.awt.Color(204, 255, 255));
        txtCriterio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioKeyReleased(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 51, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-izquierda.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tblInternar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInternar);

        btnCambiarArea.setBackground(new java.awt.Color(0, 51, 102));
        btnCambiarArea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiarArea.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarArea.setText("Cambiar de área");
        btnCambiarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarAreaActionPerformed(evt);
            }
        });

        btnDarAlta.setBackground(new java.awt.Color(0, 51, 102));
        btnDarAlta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDarAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnDarAlta.setText("Dar de alta");
        btnDarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(33, 33, 33)
                        .addComponent(btnCambiarArea)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDarAlta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 560, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)
                        .addComponent(btnCambiarArea)
                        .addComponent(btnDarAlta))
                    .addComponent(btnRegresar))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String criterio = txtCriterio.getText().trim();
        buscarPaciente(criterio);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCriterioKeyReleased

    private void btnCambiarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarAreaActionPerformed
        // TODO add your handling code here:
         int filaSeleccionada = tblInternar.getSelectedRow();
    if (filaSeleccionada >= 0) {
        String nombreCompleto = (String) tblInternar.getValueAt(filaSeleccionada, 0);
        String rfc = (String) tblInternar.getValueAt(filaSeleccionada, 1);
        String diagnostico = (String) tblInternar.getValueAt(filaSeleccionada, 3);

        CambiarArea cambiarAreaFrame = new CambiarArea();
        cambiarAreaFrame.setPacienteInfo(nombreCompleto, rfc, diagnostico);
        cambiarAreaFrame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un paciente para cambiar el área.");
    }
    }//GEN-LAST:event_btnCambiarAreaActionPerformed

    private void btnDarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarAltaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInternar.getSelectedRow();
    if (selectedRow != -1) {
        String nombre = tblInternar.getValueAt(selectedRow, 0).toString();
        String rfc = tblInternar.getValueAt(selectedRow, 1).toString();
        
        if (salidaFrame == null) {
            salidaFrame = new Salida();
            Salida vi = new Salida();
            vi.setVisible(true);
            
        }
        if (salidaFrame != null) {
            salidaFrame.setPacienteInfo(nombre, rfc);
            salidaFrame.setVisible(true);
            this.dispose(); // Cerrar el frame actual si es necesario
        } else {
            System.out.println("salidaFrame es null.");
        }
    } else {
        System.out.println("Seleccione un paciente de la tabla.");
    }
    }//GEN-LAST:event_btnDarAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verInternados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verInternados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verInternados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verInternados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verInternados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarArea;
    private javax.swing.JButton btnDarAlta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblInternar;
    private javax.swing.JTextField txtCriterio;
    // End of variables declaration//GEN-END:variables

    /*
    
     */
    private void cargarTabla() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT nombre_paciente, rfc, fecha, motivo, area, numero_piso, numero_cuarto, tratamiento "
                + "FROM internar LIMIT ? OFFSET ?";

        PreparedStatement ps;

        try {
            ps = con.prepareStatement(sql);

            int limit = 20;
            int offset = 0;

            ps.setInt(1, limit);
            ps.setInt(2, offset);

            ResultSet rs = ps.executeQuery();

            model.setColumnIdentifiers(new String[]{
                "Nombre", "RFC", "Fecha que se internó", "Diagnostico", "Área", "Número de piso", "Número de cuarto", "Tratamiento"
            });

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getString("nombre_paciente");
                fila[1] = rs.getString("rfc");
                fila[2] = rs.getDate("fecha");
                fila[3] = rs.getString("motivo");
                fila[4] = rs.getString("area");
                fila[5] = rs.getString("numero_piso");
                fila[6] = rs.getString("numero_cuarto");
                fila[7] = rs.getString("tratamiento");
                model.addRow(fila);
            }

            tblInternar.setModel(model);
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al rellenar la tabla Pacientes internados: " + e);
        }
    }

    private void buscarPaciente(String criterio) {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();

        int inicio = (paginaActual - 1) * registrosPorPagina;

        String sql = "SELECT nombre_paciente, rfc, fecha, motivo, area, numero_piso, numero_cuarto, tratamiento "
                + "FROM internar WHERE nombre_paciente LIKE ? LIMIT ? OFFSET ?";

        PreparedStatement ps;

        try {
            ps = con.prepareStatement(sql);
            ps.setString(1, "%" + criterio + "%");
            ps.setInt(2, registrosPorPagina);
            ps.setInt(3, inicio);
            ResultSet rs = ps.executeQuery();

            model.setColumnIdentifiers(new String[]{
                "Nombre", "rfc", "Fecha que se internó", "Diagnostico", "Área", "Número de piso", "Número de cuarto", "Tratamiento"
            });

            while (rs.next()) {
                Object[] fila = new Object[8];
                fila[0] = rs.getString("nombre_paciente");
                fila[1] = rs.getString("rfc");
                fila[2] = rs.getDate("fecha");
                fila[3] = rs.getString("motivo");
                fila[4] = rs.getString("area");
                fila[5] = rs.getString("numero_piso");
                fila[6] = rs.getString("numero_cuarto");
                fila[7] = rs.getString("tratamiento");
                model.addRow(fila);
            }

            tblInternar.setModel(model);
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al buscar paciente: " + e);
        }
    }
    
    public static verInternados getInstance() {
        return instance;
    }
    public static void actualizarTabla() {
    if (instance != null) {
        instance.cargarTabla();
    }
}

}
